http:
  routers:
    ocelot:
      rule: "PathPrefix(`/api`)"
      service: ocelot
      entryPoints:
        - web
    react:
      rule: "PathPrefix(`/`)"
      service: react
      entryPoints:
        - web

  services:
    ocelot:
      loadBalancer:
        servers:
          - url: "http://localhost:5180"
    react:
      loadBalancer:
        servers:
          - url: "http://localhost:9085"